name: 'idle destroyer action'
description: 'This action is used to detect releases from Github pull request labels.'
inputs:
  githubToken:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  action:
    description: 'entrypoint(notify|close)'
  ignoreLabels:
    description: 'After merged label(labelA, labelB)'
    default: ''
  baseUrl:
    description: 'Base URL for GitHub API'
    default: "https://api.github.com/repos"
  repo:
    description: '{owner}/{repo}'
    default: "${{ github.repository }}"
  slackWebhook:
    description: 'SLACK_WEBHOOK'
  notifyTemplate:
    description: |
      You can edit the template for notifications. 
      The following variables can be specified:%ISSUES%, %PULLS%, %LIMIT%, %IGNORE_LABELS%
      Similarly, if you want to mentions it, specify it.(e.g. <@USER_ID>|<!here>|<!channel>)
    default: |
      The next target is the one that will be automatically closed since %LIMIT% days have elapsed.
      If you do not want to delete it, give it a label (%IGNORE_LABELS%).

      *Issues to be closed*
      %ISSUES%

      *Pull requests to be closed*
      %PULLS%
  closedTemplate:
    description: ''
    default: |
      *Closed issues*
      %ISSUES%

      *Closed pull_requests*
      %PULLS%
  limitDays:
    description: 'Specify the number of days without update.'
    default: '180'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
  env:
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    SLACK_WEBHOOK: ${{ inputs.slackWebhook }}
    NOTIFY_TEMPLATE: ${{ inputs.notifyTemplate }}
    CLOSED_TEMPLATE: ${{ inputs.closedTemplate }}
    IGNORE_LABELS: ${{ inputs.ignoreLabels }}
    GITHUB_BASE_URL: ${{ inputs.baseUrl }}
    REPOSITORY: ${{ inputs.repo }}
    LIMIT_DAYS: ${{ inputs.limitDays }}
